name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: python cli.py --help
      - run: python setup.py sdist
      - run: sha256sum dist/*.tar.gz
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*.tar.gz
