name: Build and Release mkdfile

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: raiosystems

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build com PyInstaller
        run: |
          pyinstaller --onefile cli.py -n mkdfile
          mkdir dist-out
          cp dist/mkdfile dist-out/
          tar -czvf mkdfile-macos.tar.gz -C dist-out mkdfile

      - name: Criar Release
        uses: softprops/action-gh-release@v2
        with:
          files: mkdfile-macos.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
