name: Build and Release mkdfile

on:
  push:
    tags:
      - 'v*'  # Só roda em tags tipo v0.1.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build com PyInstaller
        run: pyinstaller --onefile cli.py -n mkdfile

      - name: Criar tar.gz
        run: |
          mkdir dist-out
          cp dist/mkdfile dist-out/
          tar -czvf mkdfile-macos.tar.gz -C dist-out mkdfile

      - name: Publicar Release
        uses: softprops/action-gh-release@v2
        with:
          files: mkdfile-macos.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}